version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    assignees:
      - "@me"
    commit-message:
      prefix: "deps"
      include: "scope"

  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    assignees:
      - "@me"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions - disabled to keep total at 2 PRs max
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
  #   open-pull-requests-limit: 1
  #   assignees:
  #     - "@me"
  #   commit-message:
  #     prefix: "ci"
  #     include: "scope"