version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=/data/license_manager.db
      - EMAIL_SERVICE=smtp
      - FROM_EMAIL=noreply@localhost
      - SMTP_SERVER=localhost
      - SMTP_PORT=587
    restart: unless-stopped